name: Release on push on master branch
 
on:
  push:
    branches:
      - master
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  release-on-push-on-master-branch:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure Git User
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Setup .Net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      
      - name: DryRun Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          dry_run: true
      
      - name: Install .Net dependencies
        run: dotnet restore ./
 
      - name: Run build
        run: dotnet build ./  --configuration Release --no-restore
 
      - name: Run publish SSI.FCData.Client
        run: |
          cd SSI.FCData.Client
          dotnet publish SSI.FCData.Client.csproj -c Release -o ../fc-data-linux.net/SSI.FCData.Client -r linux-x64 --self-contained true /p:UseAppHost=true /p:Version=${{ steps.semantic.outputs.new_release_version  }}
          dotnet publish SSI.FCData.Client.csproj -c Release -o ../fc-data.net/SSI.FCData.Client -r win-x64 --self-contained true /p:UseAppHost=true /p:Version=${{ steps.semantic.outputs.new_release_version  }}
      - name: Run publish SSI.FCData.ClientExample
        run: |
          cd SSI.FCData.ClientExample
          dotnet publish SSI.FCData.ClientExample.csproj -c Release -o ../fc-data-linux.net/SSI.FCData.ClientExample -r linux-x64 --self-contained true /p:UseAppHost=true /p:Version=${{ steps.semantic.outputs.new_release_version  }}
          dotnet publish SSI.FCData.ClientExample.csproj -c Release -o ../fc-data.net/SSI.FCData.ClientExample -r win-x64 --self-contained true /p:UseAppHost=true /p:Version=${{ steps.semantic.outputs.new_release_version  }}
 
 
      - name: ZIP target directory
        run: |
          mkdir target
          zip -r target/fc-data-win64.net.zip fc-data.net
          zip -r target/fc-data-linux64.net.zip fc-data-linux.net
 
      - name: Semantic Release
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: cycjimmy/semantic-release-action@v3